# dataset_config.yaml
name: sports_images

source: kaggle
kaggle_dataset_name: gpiosenka/sports-classification
force_download: false
root_dir: data
raw_subdir: raw
processed_subdir: processed
annotations_subdir: annotations
annotations_file: sports.csv
use_existing_train_test_split: true
train_subdir: train
val_subdir: val
test_subdir: test

input_size: [224, 224]
# normalize_mean: [0.4714, 0.4699, 0.4551]
# normalize_std: [0.2391, 0.2302, 0.2320]
augmentations:
  horizontal_flip: false
  rotation: false
  random_crop: false
  color_jitter: false
  random_resized_crop: false

batch_size: 64
shuffle: true
num_workers: 6
seed: 42
