# default.yaml
project_name: sports_cv_project_classification
experiment_name: vgg11-paper-heavy-augmentations-cosine_anealing_with_decay

# Include model and dataset configs
model: !include model_config.yaml
dataset: !include dataset_config.yaml

# Paths for outputs
checkpoints_dir: checkpoints/
logs_dir: logs/

# Training settings
training:
  optimizer:
    type: adam
    lr: 0.001
    weight_decay: 5e-4
  scheduler:
    type: cosine_annealing_warm_restarts_with_decay
    # total_steps: 100
    # pct_start: 0.25
    # max_lr: 0.001
    T_0: 25
    T_mult: 2
    eta_min: 0.
    gamma: 0.5
  loss:
    type: cross_entropy
    bbox_loss: smooth_l1
    obj_loss: binary_cross_entropy
  early_stopping:
    patience: 30
    reset_after: 25
    T_mult: 2
    threshold: 0.0001
  num_epochs: 1000
  save_best_only: true
  save_checkpoint: true
  log_interval: 50

# Evaluation
evaluation:
  metrics: [accuracy, top-5-accuracy]
  iou_threshold: 0.5
  conf_threshold: 0.3

# Misc
misc:
  device: cuda  # cpu
  seed: 42
  deterministic: true

# AWS object names
s3_bucket: computer-vision-models-pytorch-bucket
dynamodb_config_table: computer-vision-models-config-table