# model_config.yaml
model_name: VGG11
# backbone_name: VGG11
# detection_head_name: GAP
pretrained: 
  source: local
  model_part: backbone
  version_name: vgg11-gap-pretrained-w-augmenations
  freeze_time: 10

num_classes: 100
num_anchors: 3
dropout_rate: 0.5
hidden_dim: 4096
