# model_config.yaml
model_name: VGG11
# backbone_name: VGG11
# detection_head_name: GAP
pretrained:
  model_part: backbone
  experiment_name: vgg11-gap-heavy-augmentations
  save_locally: true
  freeze_time: 10

num_classes: 100
num_anchors: 3
dropout_rate: 0.5
hidden_dim: 4096
